name: "message_model_naive_experiment"

data:
    src: "src"
    trg: "trg"
    train: "data/joeynmt/messages/train"
    dev: "data/joeynmt/messages/dev"
    test: "data/joeynmt/messages/test"
    level: "word"
    lowercase: True
    max_sent_length: 50
    src_voc_min_freq: 1
    trg_voc_min_freq: 1
   
testing:
    beam_size: 1
    alpha: 1.0

training:
    random_seed: 420
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.00005
    batch_size: 10
    scheduling: "plateau"
    patience: 0
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 5
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/message_model"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 5, 10, 15, 20]

model:
    encoder:
        rnn_type: "lstm"
        embeddings: 
            embedding_dim: 256
            scale: False
        hidden_size: 256
        bidirectional: True
        dropout: 0.0
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 256
            scale: False
        emb_scale: False
        hidden_size: 256
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 1
        input_feeding: True
        init_hidden: "last"
        attention: "luong"